services:
  - type: web
    name: paystack-api
    runtime: node
    rootDir: .
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: BASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SEND_EMAIL
        value: "false"
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false

  - type: web
    name: paystack-frontend
    runtime: static
    rootDir: paystack-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_BASE_URL
        sync: false
